# Generated by Django 4.0.3 on 2022-04-23 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_frequencia',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
