# Generated by Django 4.0.3 on 2022-04-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='estadoFin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrador.estadofinanceiro'),
        ),
    ]
