# Generated by Django 4.0.3 on 2022-04-23 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_aluno_data_frequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_frequencia',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
