# Generated by Django 4.0.3 on 2022-04-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_alter_aluno_estadofin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='objetivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrador.objetivo'),
        ),
    ]
