# Generated by Django 4.0.3 on 2022-04-25 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0004_alter_aluno_data_frequencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, 'O valor deve ser maior que 0'), django.core.validators.MaxValueValidator(250)])),
                ('qntd_serie', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, 'O valor deve ser maior que 0'), django.core.validators.MaxValueValidator(250)])),
                ('repeticao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, 'O valor deve ser maior que 0'), django.core.validators.MaxValueValidator(250)])),
                ('carga', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, 'O valor deve ser maior que 0'), django.core.validators.MaxValueValidator(250)])),
                ('descanso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, 'O valor deve ser maior que 0'), django.core.validators.MaxValueValidator(250)])),
                ('comentario_ex', models.CharField(blank=True, max_length=500, null=True)),
                ('aluno_ex', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.aluno')),
                ('treino_ex', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Administrador.treino')),
            ],
        ),
    ]
