# Generated by Django 4.0.3 on 2022-04-04 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0005_remove_estadofinanceiro_d_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='estadoFin',
            new_name='estadof',
        ),
    ]
