# Generated by Django 4.0.3 on 2022-04-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0005_treino_exercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='repeticao',
        ),
    ]
