# Generated by Django 4.0.3 on 2022-04-26 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0006_remove_exercicio_repeticao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='carga',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, 'O valor deve ser maior que 0'), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='descanso',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, 'O valor deve ser maior que 0'), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='qntd_serie',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, 'O valor deve ser maior que 0'), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='serie',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, 'O valor deve ser maior que 0'), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
