# Generated by Django 4.0.3 on 2022-04-08 13:19

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0006_rename_estadofin_aluno_estadof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='rotina',
        ),
        migrations.AddField(
            model_name='professor',
            name='domingo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('manha', 'Manhã 8h-13h'), ('tarde', 'Tarde 13h-18'), ('noite', 'Noite 18h-23h'), ('folga', 'Folga')], default='folga', max_length=23),
        ),
        migrations.AddField(
            model_name='professor',
            name='quarta',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('manha', 'Manhã 8h-13h'), ('tarde', 'Tarde 13h-18'), ('noite', 'Noite 18h-23h'), ('folga', 'Folga')], default='folga', max_length=23),
        ),
        migrations.AddField(
            model_name='professor',
            name='quinta',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('manha', 'Manhã 8h-13h'), ('tarde', 'Tarde 13h-18'), ('noite', 'Noite 18h-23h'), ('folga', 'Folga')], default='folga', max_length=23),
        ),
        migrations.AddField(
            model_name='professor',
            name='sabado',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('manha', 'Manhã 8h-13h'), ('tarde', 'Tarde 13h-18'), ('noite', 'Noite 18h-23h'), ('folga', 'Folga')], default='folga', max_length=23),
        ),
        migrations.AddField(
            model_name='professor',
            name='segunda',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('manha', 'Manhã 8h-13h'), ('tarde', 'Tarde 13h-18'), ('noite', 'Noite 18h-23h'), ('folga', 'Folga')], default='folga', max_length=23),
        ),
        migrations.AddField(
            model_name='professor',
            name='sexta',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('manha', 'Manhã 8h-13h'), ('tarde', 'Tarde 13h-18'), ('noite', 'Noite 18h-23h'), ('folga', 'Folga')], default='folga', max_length=23),
        ),
        migrations.AddField(
            model_name='professor',
            name='terca',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('manha', 'Manhã 8h-13h'), ('tarde', 'Tarde 13h-18'), ('noite', 'Noite 18h-23h'), ('folga', 'Folga')], default='folga', max_length=23),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.objetivo'),
        ),
        migrations.AlterField(
            model_name='estadofinanceiro',
            name='condicao',
            field=models.CharField(choices=[('Em Dia', 'Em Dia'), ('Inadimplente', 'Inadimplente')], max_length=12),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='opcao',
            field=models.CharField(choices=[('A Selecionar', 'A Selecionar'), ('Ganhar massa muscular', 'Ganhar massa muscular'), ('Emagrecer', 'Emagrecer'), ('Ganhar resistência', 'Ganhar resistência')], max_length=21),
        ),
    ]
