# Generated by Django 4.0.3 on 2022-04-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0007_remove_professor_rotina_professor_domingo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='domingo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='quarta',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='quinta',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='sabado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='segunda',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='sexta',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='terca',
            field=models.BooleanField(),
        ),
    ]
