# Generated by Django 4.0.3 on 2022-04-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('braco_d', models.DecimalField(decimal_places=2, max_digits=5)),
                ('perna_e', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cintura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentario_af', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_pagamento', models.DateField()),
                ('condicao', models.CharField(choices=[('dia', 'Em Dia'), ('ina', 'Inadimplente')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(choices=[('musculo', 'Ganhar massa muscular'), ('emagrecer', 'Emagrecer'), ('resistencia', 'Ganhar resistência')], max_length=11)),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_u', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('frequencia', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aluno.avaliacaofisica')),
                ('estadoFin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aluno.estadofinanceiro')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aluno.objetivo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
